
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `pkg/web` directory
    directory: "/pkg/web"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "20:00"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "20:00"